name: CD
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: postdeploy
          uses: jrmcdonald/blackbox-github-actions@v0.2.0
          with:
            bb_actions_subcommand: postdeploy
          env:
            BLACKBOX_PUBKEY: ${{ secrets.BLACKBOX_PUBKEY }}
            BLACKBOX_PRIVKEY: ${{ secrets.BLACKBOX_PRIVKEY }}

        - name: share-env
          run: |
            TARGET=production yarn share-env

        - uses: superfly/flyctl-actions@1.1
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          with:
            args: deploy async

        - uses: superfly/flyctl-actions@1.1
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          with:
            args: deploy v2

        - name: shred
          uses: jrmcdonald/blackbox-github-actions@v0.2.0
          with:
            bb_actions_subcommand: shred_all_files
          env:
            BLACKBOX_PUBKEY: ${{ secrets.BLACKBOX_PUBKEY }}
            BLACKBOX_PRIVKEY: ${{ secrets.BLACKBOX_PRIVKEY }}
